### ISSUE TITLE
Make retry through Android Test Orchestrator

### ISSUE THREAD

**Issue by omen273** [omen273/crosswordApp#104]
It can help us to exclude extra code from utils.kt and tests. Please, do not forget to remove all stuff about retry from tests in case of realisation.

**Comment by greenEkatherine** [comment]
It can be done with `--num-flaky-test-attempts`

**Comment by greenEkatherine** [comment]
Unfortunately, it is possible to do it in FireBase only. Your code should be also preserved to rerun in AzDO pipeline.
