### ISSUE TITLE
Test app on tablets

### ISSUE THREAD

**Issue by greenEkatherine** [omen273/crosswordApp#112]
Google Play doesn't allow to exclude tablets from target devices. To avoid bad feedback we should test on them as well.

**Comment by omen273** [comment]
Have tested on virtual device Nexus10 API30 everything works except minors bugs with choseTopicsActivity view see https://github.com/omen273/crosswordApp/issues/119, https://github.com/omen273/crosswordApp/issues/118

**Comment by omen273** [comment]
@greenEkatherine Is it enough or you want to test more?

**Comment by greenEkatherine** [comment]
I think it's enough for now, but I would add some regular checks for tablets as well. Should I open a separate issue for it?

**Comment by omen273** [comment]
Yes, please add a separate ticket
