### ISSUE TITLE
Add the ability to choose a word by clicking on one of its already resolved letters

### ISSUE THREAD

**Issue by greenEkatherine** [omen273/crosswordApp#156]
Add the ability to choose a word by clicking on one of its already resolved letters (which are from intersected words).
It also should allow checking translation of the word even after resolving and would be useful for learning purposes.

**Comment by omen273** [comment]
We need to decide on logic how to move a cursor in case of printing if we stay on a solved letter.

**Comment by omen273** [comment]
It will be implemented in https://github.com/omen273/crosswordApp/issues/255
