### ISSUE TITLE
Update target version to api 30

### ISSUE THREAD

**Issue by omen273** [omen273/crosswordApp#223]

**Comment by greenEkatherine** [comment]
> [android/android-test#803](https://github.com/android/android-test/issues/803) I didn't find way to check toast message on api 30. So we need to switch off all tests which inhereted from BadCrosswordDataTest on api 30 for now

Only two tests? I see that 5 tests are failing

**Comment by omen273** [comment]
Sorry. You are right. It should be 5 tests withToastMatcher.onToast.
