### ISSUE TITLE
Test restore state with all activities

### ISSUE THREAD

**Issue by omen273** [omen273/crosswordApp#263]
We need to test restoreState because some crashes can be cause this scenario see https://github.com/omen273/crosswordApp/issues/244, https://github.com/omen273/crosswordApp/issues/245 How to. Ativate rotation, rotate during active activity. It won't be crashes, bugs after it.

**Comment by greenEkatherine** [comment]
All is ok except for one case, I'm not sure if it is a bug. Steps to reproduce:
0. Remove portrait orientation.
1. Open crossword.
2. Solve it.
3. Before choosing "another crossword", rotate the phone.
4. Get "Crossword data is damaged".
5. However, after rotating the phone back you will get the crossword back.

**Comment by omen273** [comment]
Solved at 276
