### ISSUE TITLE
Fix java.lang.NumberFormatException

### ISSUE THREAD

**Issue by omen273** [omen273/crosswordApp#301]
https://dev.azure.com/warpedomen/warpedomen/_build/results?buildId=730&view=ms.vss-test-web.build-test-results-tab&runId=9292&resultId=100020&paneView=debug It looks like it is possible to have FREE word in 579 line GameActivity. It is need to check that it is possible to transform string to int otherwise get starNumber from class and use it

**Comment by greenEkatherine** [comment]
Also fix logic with free hints - words vs cells
