### ISSUE TITLE
Fix DeleteCrosswordAfterSolveInstrumentedTest 

### ISSUE THREAD

**Issue by greenEkatherine** [omen273/crosswordApp#38]
`IMAGE_DIRECTORY` doesn't exist at the moment of first call `getLastCrossword`. `saveScreenshot` is called later - I've added in both methods debug log and attached the result
[DeleteCrosswordAfterSolveInstrumentedTest.zip](https://github.com/omen273/crosswordApp/files/5743429/DeleteCrosswordAfterSolveInstrumentedTest.zip)

**Comment by greenEkatherine** [comment]
- [ ] don't forget to remove debug log

**Comment by omen273** [comment]
I think we have some problems with creation of drawble folder on Azure because of absence of rights. I had added waitForCondition("", {imagesPath.exists()}) and it didn't help. This function would have excluded asynchrony. So in my opinion, the most probable reason of failure is rights.

**Comment by omen273** [comment]
My invistigations shown that app doesn't need additional permissions to write to an external storage https://developer.android.com/training/data-storage. If I remeber correctly @greenEkatherine solved problems with permissions in case of githab actions.

**Comment by greenEkatherine** [comment]
After saving logs related to API it's finally clear that there are two different issues. The first one - **media is not mounted on API 21-23**. The second one probably fixed by https://github.com/omen273/crosswordApp/pull/77 I will rerun jobs for our draft PR several times to confirm that.

**Comment by greenEkatherine** [comment]
I've opened #83 to fix media mounting

**Comment by omen273** [comment]
Closed as will be fixed in differernt tickets
