### ISSUE TITLE
Fix DeleteCrosswordInstrumentedTest 

### ISSUE THREAD

**Issue by greenEkatherine** [omen273/crosswordApp#42]
The test is failed because on VM we open the wrong crossword. Probably it is because we don't open the main activity after the crossword removed.  Need to be reproduced locally and further investigation.
Video 00:35 - 01:09

https://user-images.githubusercontent.com/19972657/103159018-8d9d7200-47c4-11eb-9b17-7e2c60cd44f5.mp4

**Comment by greenEkatherine** [comment]
Based on the last ~10 builds this test always passed on API 25

**Comment by greenEkatherine** [comment]
Next I'm going to publish test results in a pipeline in scope of this task https://github.com/omen273/crosswordApp/issues/51

**Comment by omen273** [comment]
It has different reason so splitted into several issues.
