### ISSUE TITLE
java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.ImageView

### ISSUE THREAD

**Issue by greenEkatherine** [omen273/crosswordApp#59]
6 tests failed now with exception:

`	java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.ImageView
	at com.example.crosswordToLearn.MainActivity.rightShift(MainActivity.kt:315)
`
Failed tests:

- SolvedCrosswordAfterFillInstrumentedTest
- BadCrosswordStateInstrumentedTest
- DeleteCrosswordAfterSolveInstrumentedTest
- DeleteCrosswordInstrumentedTest
- SolveCrosswordAfterResetInstrumentedTest
- SolveCrosswordWithTipsInstrumentedTest

Build example https://dev.azure.com/warpedomen/warpedomen/_build/results?buildId=52&view=logs&j=111e99dd-f0c5-5956-a710-885b7913b218&t=539fca6e-a781-5132-22c9-59818cea9504&l=34894

**Comment by omen273** [comment]
I think the main reason of this bug is rights. But we need to add exception handling.

**Comment by greenEkatherine** [comment]
this should be resolved now by #76

**Comment by greenEkatherine** [comment]
resolved
