### ISSUE TITLE
Add level of the words to the topic

### ISSUE THREAD

**Issue by greenEkatherine** [omen273/crosswordApp#70]
Idea for enhancement - I will add it as an issue if you find it interesting. I think it would be good to add also level of the words to the topic. Because when you learn you should choose the proper complexity

_Originally posted by @greenEkatherine in https://github.com/omen273/crosswordApp/issues/69#issuecomment-762465811_

**Comment by omen273** [comment]
I agree with this idea. We can realise it if the first realease will be successful.

**Comment by omen273** [comment]
integration branch for this feature has been created https://github.com/omen273/crosswordApp/issues/167 167-Add-levels-and-new-words
